Models/CreateNewDeveloperViewModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace mvcSaltTraining.Models;

public class CreateNewDeveloperViewModel
{
  [DisplayName("Developer name")]
  [Required]
  public string? Name { get; set; }

  [DisplayName("Email address")]
  [Required]
  [EmailAddress]
  public string? Email { get; set; }
}

Models/Developer.cs
namespace mvcSaltTraining.Models;
public class Developer{

    public int ID {get; set;}
    public string Name {get; set;} = "No Name";
    public string Email {get; set;} = "nomail@found.com";

}

Models/ErrorViewModel.cs
namespace mvcSaltTraining.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Controllers/DevelopersController.cs
using System.Data.Common;
using Microsoft.AspNetCore.Mvc;
using mvcSaltTraining.Models;

namespace mvcSaltTraining.Controllers;

public class DevelopersController : Controller
{
    private Db _db;
    public DevelopersController(Db db)
    {
        _db = db;
    }

    public IActionResult Index (){
        return View(_db.Developers);
    }

    public IActionResult Details (int id)
    {
       var developer = _db.Developers.Find(dev => dev.ID == id);
        return View(developer);
    }

    public IActionResult Create ()
    {
        return View();
    }

    [HttpPost]
public IActionResult Create(CreateNewDeveloperViewModel viewModel)
{
  var nextId = _db.Developers.Count;
  var developerToAdd = new Developer()
  {
    ID = nextId,
    Name = viewModel.Name,
    Email = viewModel.Email
  };
  _db.Developers.Add(developerToAdd);

  return RedirectToAction(nameof(Index));
  // return RedirectToAction(nameof(Details), new { Id = nextId });
}
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using mvcSaltTraining.Models;

namespace mvcSaltTraining.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Views/Developers/Create.cshtml
@model CreateNewDeveloperViewModel

<h1>Add a new developer</h1>

<form asp-controller="Developers" asp-action="Create" method="post">
  @Html.DisplayNameFor(m => m.Name): <input asp-for="Name" /> <br />
  @Html.DisplayNameFor(m => m.Email): <input asp-for="Email" /> <br />
  <button type="submit">Create new developer</button>
</form>

Views/Developers/Details.cshtml
@model Developer

<h1> Developer Details </h1>
<h2> @Model.Name </h2>

<ul>
    <li>@Html.DisplayNameFor(m => m.ID) : @Model.ID</li>
  <li>@Html.DisplayNameFor(m => m.Email) : @Model.Email</li>
</ul>

<a asp-controller="Developers" asp-action="Index"> Back </a>

Views/Developers/Index.cshtml
@model List<Developer>;

<h1>Showing @Model.Count developers!</h1>
</Developer>
<h1>All developers</h1>
<a asp-controller="Developers" asp-action="Create"> Create </a>
<table>
    <thead>
        <tr>
            <th> ID </th>
            <th> Name </th>
            <th> Email </th>
            <th> Details </th>
        </tr>
    </thead>
    <tbody>
        @{
            foreach (var i in @Model)
            {
                <tr>
                    <td>@i.ID</td>
                    <td>@i.Name</td>
                    <td>@i.Email</td>
                    <td><a asp-controller="Developers" asp-action="Details" asp-route-id="@i.ID"> Details </a></td>
                </tr>
            }
        }
    </tbody>
</table>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - mvcSaltTraining</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/mvcSaltTraining.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">mvcSaltTraining</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - mvcSaltTraining - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>